### PR TITLE
feat: data augmentation while training models

### PR DESCRIPTION
**Pull request by hasibzunair**
Adds function which augments data during training.

### CODE REVIEW

**Comment by hasibzunair** [comment]
Not sure how to fix the PEP8 issue. I've formatted the script using `autopep8 filename.py --in-place`.

**Comment by yangobeil** [comment]
> Not sure how to fix the PEP8 issue. I've formatted the script using `autopep8 filename.py --in-place`.

This message is because there is a try/except where the except doesn't specify what error types to look for. This is not favored but we can leave it like that.

**Comment by yangobeil** [comment]
Can you please add a parameter in the class to decide if we augment the data? It can be set to True by default but it's good to have it for people who want to use the offline augmentation feature of the library for reproducability purposes for example.

**Comment by hasibzunair** [comment]
Added.

**Review by yangobeil — APPROVED** [review]
I tested it and it seems to work well. Thanks for the nice addition!

**Comment by hasibzunair** [comment]
Yay!

**Pull request merged**
